on: workflow_dispatch

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          ort-config-repository: 'https://github.com/daniel-eder/ort-config'
          # manually set steps to run to include scanner
          default: > 
            cache-dependencies,
            metadata-labels,
            analyzer,
            scanner,
            reporter,
            upload-results,
            upload-evaluation-result
      - name: 
        id: print-result-tree
        run: tree -d ~/.ort > ~/result.tree.txt
      - uses: actions/upload-artifact@v3
        with:
          name: result.tree.txt
          path: ~/result.tree.txt
       